//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace bingo {
    
    
    public partial class Default {
        
        /// <summary>
        /// ucSlide control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bingo.Module.ucSlide ucSlide;
        
        /// <summary>
        /// ucArticle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bingo.Module.ucArticle ucArticle;
        
        /// <summary>
        /// ucLopSapKhaiGiang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bingo.Module.ucLopSapKhaiGiang ucLopSapKhaiGiang;
    }
}
